CREATE DATABASE QuanLyBanHang;
GO
USE QuanLyBanHang;
GO
CREATE TABLE KhachHang (
    MaKH INT PRIMARY KEY,
    TenKH NVARCHAR(100)
);
CREATE TABLE SanPham (
    MaSP INT PRIMARY KEY,
    TenSP NVARCHAR(100),
    Gia FLOAT
);
CREATE TABLE DonHang (
    MaDH INT PRIMARY KEY,
    MaKH INT,
    NgayDat DATE,
    FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);
CREATE TABLE ChiTietDonHang (
    MaDH INT,
    MaSP INT,
    SoLuong INT,
    PRIMARY KEY (MaDH, MaSP),
    FOREIGN KEY (MaDH) REFERENCES DonHang(MaDH),
    FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP)
);
INSERT INTO KhachHang VALUES (1, N'Nguyễn Văn B');
INSERT INTO SanPham VALUES (101, N'Laptop', 15000000);
INSERT INTO DonHang VALUES (1001, 1, GETDATE());
INSERT INTO ChiTietDonHang VALUES (1001, 101, 2);
